[destination.snowflake.credentials]
username = "MATTEUS"
password = "GAB_riel_12345"
account = "UF31763.westeurope.azure"
database = "ARBETSKOLLEN"
warehouse = "COMPUTE_WH"
schema = "mart"
role = "ACCOUNTADMIN"
host = "gj47783.west-europe.azure"

